### ISSUE TITLE
No email sent

### ISSUE THREAD

**Issue by anthonymontebrun** [ticgal/mfa#1]
Hello, 

I have configure the plugin, but no email sent.
No notifications in the notification queue, I did not find any log.
I use GLPI Database Authentication, with an email on the account.

Sincerely,

**Comment by wmeneses** [comment]
> 

+1

**Comment by xacobofg** [comment]
Hi @anthonymontebrun 
Can you test if the commit https://github.com/ticgal/mfa/commit/dff12755653426d1a8d5a719d66eeaf0d05bdc7d  fixes the error?

**Comment by anthonymontebrun** [comment]
Hello,

I confirm the commit fixe the error.

Thanks.
