### ISSUE TITLE
How can I install it?

### ISSUE THREAD

**Issue by cmmata** [ticgal/mfa#5]
Hi,

I can see almost all your other plugins on the marketplace, but I cannot see this one. How can I install it?

I tried to download the zip and put it in `glpi/plugins` directory, but I don't see anything changed in marketplace page.

Sorry if this is a newbie question, I just discovered and installed GLPI last week. Thank you in advance!

**Comment by OscarBeiro** [comment]
Hi,
Thanks for the report. We weren't aware  about the plugin not being accessible through the marketplace, as it is published at the plugins website.
I will contact Teclib and see if they can help.
Meanwhile install it like any other plugin: https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/plugins.html

Regards,

**Comment by cmmata** [comment]
It's weird, because I already unzipped the plugin on the `plugins` directory, and I didn't see it in GLPI. But if it's “the way” of installing plugins outside the marketplace, I'll try again. Maybe I did something wrong 👍🏻

**Comment by OscarBeiro** [comment]
That makes sense.
Don't ever use the source code.
Get the release tar.tgz
https://github.com/ticgal/mfa/releases/download/1.0.1/glpi-mfa-1.0.1.tar.tgz
Regards
