### ISSUE TITLE
Item not found (https://xxxxxxxx/config.form.php)

### ISSUE THREAD

**Issue by killian133** [ticgal/mfa#8]
Hello,

I was looking for a plugin to enable two-factor authentication and I came across yours and it looks fantastic.
However I have a problem after having copied and pasted all the files and directories in the root of my GLPI directory.
I get this message which appears when I go to "Setup->General". 
It's normal ? Is there something I haven't done?
![configform](https://github.com/ticgal/mfa/assets/94191579/76073ae8-9e1c-4682-a661-5eeddfbe1d49)

Regards,
Killian

**Comment by killian133** [comment]
problem solved, I had not installed the files in "plugins" folder..

**Comment by OscarBeiro** [comment]
Thanks for the feedback.
It is one of the GLPI basics :)
